version: "3.8"

services:
  event-backend:
    build:
      context: . 
    container_name: eventbrite-app-backend
    image: rekha1490/eventbrite-backend:latest
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c", "sleep 10 && npm start"]
    restart: always
    environment:
      PGHOST: db
      PGPORT: "5432"
      PGUSER: rekha
      PGPASSWORD: mypassword
      PGDATABASE: eventmanagement
    ports:
      - "5060:3001"
    networks:
      - eventapp-network

  db: 
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: rekha
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: eventmanagement
    ports:
      - "5434:5432"  
    networks: 
      - eventapp-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d eventmanagement -U rekha || exit 1"]
      interval: 10s
      retries: 5
      start_period: 30s
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  eventapp-network:
    name: eventapp-network

volumes:
  postgres_data:

